export const ROLES = [
  { value: 'USER', label: '一般用戶' },
  { value: 'SPONSOR', label: '贊助商' },
  { value: 'ADMIN', label: '管理員' }
] as const;

export const POSITIONS = [
  { value: 'NONE', label: '無特定位置' },
  { value: 'SPIKER', label: '攻擊手' },
  { value: 'SETTER', label: '舉球員' },
  { value: 'LIBERO', label: '自由球員' }
] as const;

export const LEVELS = [
  { value: 'BEGINNER', label: '初學者' },
  { value: 'INTERMEDIATE', label: '中級' },
  { value: 'ADVANCED', label: '高級' },
  { value: 'EXPERT', label: '專業' }
] as const;

export const GENDERS = [
  { value: 'MALE', label: '男性' },
  { value: 'FEMALE', label: '女性' }
] as const;

export const NET_TYPES = [
  { value: 'MEN', label: '男網' },
  { value: 'WOMEN', label: '女網' },
  { value: 'MIXED', label: '混網' }
] as const;

export const LOCATIONS = {
  cities: [
    {
      id: "taipei",
      name: "臺北市",
      code: "taipei",
      districts: [
        { id: "zhongzheng", name: "中正區", code: "zhongzheng" },
        { id: "datong", name: "大同區", code: "datong" },
        { id: "zhongshan", name: "中山區", code: "zhongshan" },
        { id: "songshan", name: "松山區", code: "songshan" },
        { id: "daan", name: "大安區", code: "daan" },
        { id: "wanhua", name: "萬華區", code: "wanhua" },
        { id: "xinyi", name: "信義區", code: "xinyi" },
        { id: "shilin", name: "士林區", code: "shilin" },
        { id: "beitou", name: "北投區", code: "beitou" },
        { id: "neihu", name: "內湖區", code: "neihu" },
        { id: "nangang", name: "南港區", code: "nangang" },
        { id: "wenshan", name: "文山區", code: "wenshan" },
      ],
    },
    {
      id: "newtaipei",
      name: "新北市",
      code: "newtaipei",
      districts: [
        { id: "banqiao", name: "板橋區", code: "banqiao" },
        { id: "sanchong", name: "三重區", code: "sanchong" },
        { id: "zhonghe", name: "中和區", code: "zhonghe" },
        { id: "yonghe", name: "永和區", code: "yonghe" },
        { id: "xinzhuang", name: "新莊區", code: "xinzhuang" },
        { id: "xindian", name: "新店區", code: "xindian" },
        { id: "shulin", name: "樹林區", code: "shulin" },
        { id: "yingge", name: "鶯歌區", code: "yingge" },
        { id: "sanxia", name: "三峽區", code: "sanxia" },
        { id: "tamsui", name: "淡水區", code: "tamsui" },
        { id: "xizhi", name: "汐止區", code: "xizhi" },
        { id: "ruifang", name: "瑞芳區", code: "ruifang" },
        { id: "tucheng", name: "土城區", code: "tucheng" },
        { id: "luzhou", name: "蘆洲區", code: "luzhou" },
        { id: "wugu", name: "五股區", code: "wugu" },
        { id: "taishan", name: "泰山區", code: "taishan" },
        { id: "linkou", name: "林口區", code: "linkou" },
        { id: "shenkeng", name: "深坑區", code: "shenkeng" },
        { id: "shiding", name: "石碇區", code: "shiding" },
        { id: "pinglin", name: "坪林區", code: "pinglin" },
        { id: "sanzhi", name: "三芝區", code: "sanzhi" },
        { id: "shimen", name: "石門區", code: "shimen" },
        { id: "bali", name: "八里區", code: "bali" },
        { id: "pingxi", name: "平溪區", code: "pingxi" },
        { id: "shuangxi", name: "雙溪區", code: "shuangxi" },
        { id: "gongliao", name: "貢寮區", code: "gongliao" },
        { id: "jinshan", name: "金山區", code: "jinshan" },
        { id: "wanli", name: "萬里區", code: "wanli" },
        { id: "wulai", name: "烏來區", code: "wulai" },
      ],
    },
    {
      id: "keelung",
      name: "基隆市",
      code: "keelung",
      districts: [
        { id: "renai", name: "仁愛區", code: "renai" },
        { id: "xinyi", name: "信義區", code: "xinyi" },
        { id: "zhongzheng", name: "中正區", code: "zhongzheng" },
        { id: "zhongshan", name: "中山區", code: "zhongshan" },
        { id: "anle", name: "安樂區", code: "anle" },
        { id: "nuannuan", name: "暖暖區", code: "nuannuan" },
        { id: "qidu", name: "七堵區", code: "qidu" },
      ],
    },
    {
      id: "taoyuan",
      name: "桃園市",
      code: "taoyuan",
      districts: [
        { id: "taoyuan", name: "桃園區", code: "taoyuan" },
        { id: "zhongli", name: "中壢區", code: "zhongli" },
        { id: "pingzhen", name: "平鎮區", code: "pingzhen" },
        { id: "bade", name: "八德區", code: "bade" },
        { id: "yangmei", name: "楊梅區", code: "yangmei" },
        { id: "luzhu", name: "蘆竹區", code: "luzhu" },
        { id: "dayuan", name: "大園區", code: "dayuan" },
        { id: "guishan", name: "龜山區", code: "guishan" },
        { id: "daxi", name: "大溪區", code: "daxi" },
        { id: "longtan", name: "龍潭區", code: "longtan" },
        { id: "xinwu", name: "新屋區", code: "xinwu" },
        { id: "guanyin", name: "觀音區", code: "guanyin" },
        { id: "fuxing", name: "復興區", code: "fuxing" },
      ],
    },
    {
      id: "hsinchu_city",
      name: "新竹市",
      code: "hsinchu_city",
      districts: [
        { id: "east", name: "東區", code: "east" },
        { id: "north", name: "北區", code: "north" },
        { id: "xiangshan", name: "香山區", code: "xiangshan" },
      ],
    },
    {
      id: "hsinchu_county",
      name: "新竹縣",
      code: "hsinchu_county",
      districts: [
        { id: "zhubei", name: "竹北市", code: "zhubei" },
        { id: "zhudong", name: "竹東鎮", code: "zhudong" },
        { id: "xinpu", name: "新埔鎮", code: "xinpu" },
        { id: "guanxi", name: "關西鎮", code: "guanxi" },
        { id: "hukou", name: "湖口鄉", code: "hukou" },
        { id: "xinfeng", name: "新豐鄉", code: "xinfeng" },
        { id: "qionglin", name: "芎林鄉", code: "qionglin" },
        { id: "hengshan", name: "橫山鄉", code: "hengshan" },
        { id: "beipu", name: "北埔鄉", code: "beipu" },
        { id: "baoshan", name: "寶山鄉", code: "baoshan" },
        { id: "emei", name: "峨眉鄉", code: "emei" },
        { id: "jianshi", name: "尖石鄉", code: "jianshi" },
        { id: "wufeng", name: "五峰鄉", code: "wufeng" },
      ],
    },
    {
      id: "miaoli",
      name: "苗栗縣",
      code: "miaoli",
      districts: [
        { id: "miaoli", name: "苗栗市", code: "miaoli" },
        { id: "yuanli", name: "苑裡鎮", code: "yuanli" },
        { id: "tongxiao", name: "通霄鎮", code: "tongxiao" },
        { id: "zhunan", name: "竹南鎮", code: "zhunan" },
        { id: "toufen", name: "頭份市", code: "toufen" },
        { id: "houlong", name: "後龍鎮", code: "houlong" },
        { id: "zhuolan", name: "卓蘭鎮", code: "zhuolan" },
        { id: "dahu", name: "大湖鄉", code: "dahu" },
        { id: "gongguan", name: "公館鄉", code: "gongguan" },
        { id: "tongluo", name: "銅鑼鄉", code: "tongluo" },
        { id: "nanzhuang", name: "南庄鄉", code: "nanzhuang" },
        { id: "touwu", name: "頭屋鄉", code: "touwu" },
        { id: "sanwan", name: "三灣鄉", code: "sanwan" },
        { id: "sanxi", name: "三義鄉", code: "sanxi" },
        { id: "xihu", name: "西湖鄉", code: "xihu" },
        { id: "zaoqiao", name: "造橋鄉", code: "zaoqiao" },
        { id: "shitan", name: "獅潭鄉", code: "shitan" },
        { id: "taian", name: "泰安鄉", code: "taian" },
      ],
    },
    {
      id: "taichung",
      name: "臺中市",
      code: "taichung",
      districts: [
        { id: "central", name: "中區", code: "central" },
        { id: "east", name: "東區", code: "east" },
        { id: "south", name: "南區", code: "south" },
        { id: "west", name: "西區", code: "west" },
        { id: "north", name: "北區", code: "north" },
        { id: "xitun", name: "西屯區", code: "xitun" },
        { id: "nantun", name: "南屯區", code: "nantun" },
        { id: "beitun", name: "北屯區", code: "beitun" },
        { id: "fengyuan", name: "豐原區", code: "fengyuan" },
        { id: "dongshi", name: "東勢區", code: "dongshi" },
        { id: "dajia", name: "大甲區", code: "dajia" },
        { id: "qingshui", name: "清水區", code: "qingshui" },
        { id: "shalu", name: "沙鹿區", code: "shalu" },
        { id: "wuqi", name: "梧棲區", code: "wuqi" },
        { id: "houli", name: "后里區", code: "houli" },
        { id: "shengang", name: "神岡區", code: "shengang" },
        { id: "tanzi", name: "潭子區", code: "tanzi" },
        { id: "daya", name: "大雅區", code: "daya" },
        { id: "xinshe", name: "新社區", code: "xinshe" },
        { id: "shigang", name: "石岡區", code: "shigang" },
        { id: "waipu", name: "外埔區", code: "waipu" },
        { id: "daan_taichung", name: "大安區", code: "daan_taichung" },
        { id: "wuri", name: "烏日區", code: "wuri" },
        { id: "dadu", name: "大肚區", code: "dadu" },
        { id: "longjing", name: "龍井區", code: "longjing" },
        { id: "wufeng_taichung", name: "霧峰區", code: "wufeng_taichung" },
        { id: "taiping", name: "太平區", code: "taiping" },
        { id: "dali", name: "大里區", code: "dali" },
        { id: "heping", name: "和平區", code: "heping" },
      ],
    },
    {
      id: "changhua",
      name: "彰化縣",
      code: "changhua",
      districts: [
        { id: "changhua", name: "彰化市", code: "changhua" },
        { id: "yuanlin", name: "員林市", code: "yuanlin" },
        { id: "lugang", name: "鹿港鎮", code: "lugang" },
        { id: "hemei", name: "和美鎮", code: "hemei" },
        { id: "xianxi", name: "線西鄉", code: "xianxi" },
        { id: "shengang_changhua", name: "伸港鄉", code: "shengang_changhua" },
        { id: "fuxing_changhua", name: "福興鄉", code: "fuxing_changhua" },
        { id: "xiushui", name: "秀水鄉", code: "xiushui" },
        { id: "huatan", name: "花壇鄉", code: "huatan" },
        { id: "fenyuan", name: "芬園鄉", code: "fenyuan" },
        { id: "dacun", name: "大村鄉", code: "dacun" },
        { id: "puxin", name: "埔心鄉", code: "puxin" },
        { id: "puyan", name: "埔鹽鄉", code: "puyan" },
        { id: "tianwei", name: "田尾鄉", code: "tianwei" },
        { id: "beidou", name: "北斗鎮", code: "beidou" },
        { id: "tianzhong", name: "田中鎮", code: "tianzhong" },
        { id: "shetou", name: "社頭鄉", code: "shetou" },
        { id: "tianzhong_town", name: "田中鎮", code: "tianzhong_town" },
        { id: "yongjing", name: "永靖鄉", code: "yongjing" },
        { id: "xizhou", name: "溪州鄉", code: "xizhou" },
        { id: "pitou", name: "埤頭鄉", code: "pitou" },
        { id: "xihu_changhua", name: "溪湖鎮", code: "xihu_changhua" },
        { id: "erlin", name: "二林鎮", code: "erlin" },
        { id: "dacheng", name: "大城鄉", code: "dacheng" },
        { id: "fangyuan", name: "芳苑鄉", code: "fangyuan" },
        { id: "zhutang", name: "竹塘鄉", code: "zhutang" },
        { id: "ershui", name: "二水鄉", code: "ershui" },
      ],
    },
    {
      id: "nantou",
      name: "南投縣",
      code: "nantou",
      districts: [
        { id: "nantou", name: "南投市", code: "nantou" },
        { id: "puli", name: "埔里鎮", code: "puli" },
        { id: "caotun", name: "草屯鎮", code: "caotun" },
        { id: "zhushan", name: "竹山鎮", code: "zhushan" },
        { id: "jiji", name: "集集鎮", code: "jiji" },
        { id: "mingjian", name: "名間鄉", code: "mingjian" },
        { id: "lugu", name: "鹿谷鄉", code: "lugu" },
        { id: "zhongliao", name: "中寮鄉", code: "zhongliao" },
        { id: "yuchi", name: "魚池鄉", code: "yuchi" },
        { id: "guoxing", name: "國姓鄉", code: "guoxing" },
        { id: "shuili", name: "水里鄉", code: "shuili" },
        { id: "xinyi_nantou", name: "信義鄉", code: "xinyi_nantou" },
        { id: "renai_nantou", name: "仁愛鄉", code: "renai_nantou" },
      ],
    },
    {
      id: "yunlin",
      name: "雲林縣",
      code: "yunlin",
      districts: [
        { id: "douliu", name: "斗六市", code: "douliu" },
        { id: "dounan", name: "斗南鎮", code: "dounan" },
        { id: "huwei", name: "虎尾鎮", code: "huwei" },
        { id: "xiluo", name: "西螺鎮", code: "xiluo" },
        { id: "tuku", name: "土庫鎮", code: "tuku" },
        { id: "beigang", name: "北港鎮", code: "beigang" },
        { id: "gukeng", name: "古坑鄉", code: "gukeng" },
        { id: "dapi", name: "大埤鄉", code: "dapi" },
        { id: "citong", name: "莿桐鄉", code: "citong" },
        { id: "linnei", name: "林內鄉", code: "linnei" },
        { id: "erlun", name: "二崙鄉", code: "erlun" },
        { id: "lunbei", name: "崙背鄉", code: "lunbei" },
        { id: "mailiao", name: "麥寮鄉", code: "mailiao" },
        { id: "dongshi_yunlin", name: "東勢鄉", code: "dongshi_yunlin" },
        { id: "baozhong", name: "褒忠鄉", code: "baozhong" },
        { id: "taixi", name: "臺西鄉", code: "taixi" },
        { id: "yuanchang", name: "元長鄉", code: "yuanchang" },
        { id: "sihu", name: "四湖鄉", code: "sihu" },
        { id: "kouhu", name: "口湖鄉", code: "kouhu" },
        { id: "shuilin", name: "水林鄉", code: "shuilin" },
      ],
    },
    {
      id: "chiayi_city",
      name: "嘉義市",
      code: "chiayi_city",
      districts: [
        { id: "east", name: "東區", code: "east" },
        { id: "west", name: "西區", code: "west" },
      ],
    },
    {
      id: "chiayi_county",
      name: "嘉義縣",
      code: "chiayi_county",
      districts: [
        { id: "taibao", name: "太保市", code: "taibao" },
        { id: "puzi", name: "朴子市", code: "puzi" },
        { id: "budai", name: "布袋鎮", code: "budai" },
        { id: "dalin", name: "大林鎮", code: "dalin" },
        { id: "minxiong", name: "民雄鄉", code: "minxiong" },
        { id: "xikou", name: "溪口鄉", code: "xikou" },
        { id: "xingang", name: "新港鄉", code: "xingang" },
        { id: "liujiao", name: "六腳鄉", code: "liujiao" },
        { id: "dongshi_chiayi", name: "東石鄉", code: "dongshi_chiayi" },
        { id: "yijhu", name: "義竹鄉", code: "yijhu" },
        { id: "lucao", name: "鹿草鄉", code: "lucao" },
        { id: "shuishang", name: "水上鄉", code: "shuishang" },
        { id: "zhongpu", name: "中埔鄉", code: "zhongpu" },
        { id: "zhuqi", name: "竹崎鄉", code: "zhuqi" },
        { id: "meishan", name: "梅山鄉", code: "meishan" },
        { id: "fanlu", name: "番路鄉", code: "fanlu" },
        { id: "dapu", name: "大埔鄉", code: "dapu" },
        { id: "alishan", name: "阿里山鄉", code: "alishan" },
      ],
    },
    {
      id: "tainan",
      name: "臺南市",
      code: "tainan",
      districts: [
        { id: "zhongxi", name: "中西區", code: "zhongxi" },
        { id: "east", name: "東區", code: "east" },
        { id: "south", name: "南區", code: "south" },
        { id: "north", name: "北區", code: "north" },
        { id: "anping", name: "安平區", code: "anping" },
        { id: "annan", name: "安南區", code: "annan" },
        { id: "yongkang", name: "永康區", code: "yongkang" },
        { id: "guiren", name: "歸仁區", code: "guiren" },
        { id: "xinhua", name: "新化區", code: "xinhua" },
        { id: "zuozhen", name: "左鎮區", code: "zuozhen" },
        { id: "yujing", name: "玉井區", code: "yujing" },
        { id: "nanxi", name: "楠西區", code: "nanxi" },
        { id: "nanhua", name: "南化區", code: "nanhua" },
        { id: "rende_tainan", name: "仁德區", code: "rende_tainan" },
        { id: "guanmiao", name: "關廟區", code: "guanmiao" },
        { id: "longqi", name: "龍崎區", code: "longqi" },
        { id: "yongkang_dist", name: "官田區", code: "guantian" },
        { id: "madou", name: "麻豆區", code: "madou" },
        { id: "jiali", name: "佳里區", code: "jiali" },
        { id: "xigang", name: "西港區", code: "xigang" },
        { id: "qigu", name: "七股區", code: "qigu" },
        { id: "jiangjun", name: "將軍區", code: "jiangjun" },
        { id: "xuejia", name: "學甲區", code: "xuejia" },
        { id: "beimen", name: "北門區", code: "beimen" },
        { id: "xinying", name: "新營區", code: "xinying" },
        { id: "houbi", name: "後壁區", code: "houbi" },
        { id: "baihe", name: "白河區", code: "baihe" },
        { id: "dongshan", name: "東山區", code: "dongshan" },
        { id: "liujia", name: "六甲區", code: "liujia" },
        { id: "xiaying", name: "下營區", code: "xiaying" },
        { id: "liuying", name: "柳營區", code: "liuying" },
        { id: "yanshui", name: "鹽水區", code: "yanshui" },
        { id: "shanshang", name: "山上區", code: "shanshang" },
        { id: "danei", name: "大內區", code: "danei" },
        { id: "shanhua", name: "善化區", code: "shanhua" },
        { id: "anding", name: "安定區", code: "anding" },
      ],
    },
    {
      id: "kaohsiung",
      name: "高雄市",
      code: "kaohsiung",
      districts: [
        { id: "xinxing", name: "新興區", code: "xinxing" },
        { id: "qianjin", name: "前金區", code: "qianjin" },
        { id: "lingya", name: "苓雅區", code: "lingya" },
        { id: "yancheng", name: "鹽埕區", code: "yancheng" },
        { id: "gushan", name: "鼓山區", code: "gushan" },
        { id: "qijin", name: "旗津區", code: "qijin" },
        { id: "qianzhen", name: "前鎮區", code: "qianzhen" },
        { id: "sanmin", name: "三民區", code: "sanmin" },
        { id: "nanzi", name: "楠梓區", code: "nanzi" },
        { id: "xiaogang", name: "小港區", code: "xiaogang" },
        { id: "zuoying", name: "左營區", code: "zuoying" },
        { id: "renwu", name: "仁武區", code: "renwu" },
        { id: "dashe", name: "大社區", code: "dashe" },
        { id: "niaosong", name: "鳥松區", code: "niaosong" },
        { id: "gangshan", name: "岡山區", code: "gangshan" },
        { id: "qiaotou", name: "橋頭區", code: "qiaotou" },
        { id: "yanchao", name: "燕巢區", code: "yanchao" },
        { id: "tianliao", name: "田寮區", code: "tianliao" },
        { id: "alin", name: "阿蓮區", code: "alin" },
        { id: "luzhu_kaohsiung", name: "路竹區", code: "luzhu_kaohsiung" },
        { id: "hunei", name: "湖內區", code: "hunei" },
        { id: "qieding", name: "茄萣區", code: "qieding" },
        { id: "yongAn", name: "永安區", code: "yongAn" },
        { id: "mituo", name: "彌陀區", code: "mituo" },
        { id: "ziguan", name: "梓官區", code: "ziguan" },
        { id: "dashu", name: "大樹區", code: "dashu" },
        { id: "qishan", name: "旗山區", code: "qishan" },
        { id: "meinong", name: "美濃區", code: "meinong" },
        { id: "liugui", name: "六龜區", code: "liugui" },
        { id: "neimen", name: "內門區", code: "neimen" },
        { id: "shanlin", name: "杉林區", code: "shanlin" },
        { id: "jiaxian", name: "甲仙區", code: "jiaxian" },
        { id: "taoyuan_kaohsiung", name: "桃源區", code: "taoyuan_kaohsiung" },
        { id: "namasia", name: "那瑪夏區", code: "namasia" },
        { id: "maolin", name: "茂林區", code: "maolin" },
        { id: "fengshan", name: "鳳山區", code: "fengshan" },
        { id: "daliao", name: "大寮區", code: "daliao" },
        { id: "linyuan", name: "林園區", code: "linyuan" },
      ],
    },
    {
      id: "pingtung",
      name: "屏東縣",
      code: "pingtung",
      districts: [
        { id: "pingtung", name: "屏東市", code: "pingtung" },
        { id: "chaozhou", name: "潮州鎮", code: "chaozhou" },
        { id: "donggang", name: "東港鎮", code: "donggang" },
        { id: "hengchun", name: "恆春鎮", code: "hengchun" },
        { id: "wangen", name: "萬丹鄉", code: "wangen" },
        { id: "changzhi", name: "長治鄉", code: "changzhi" },
        { id: "linluo", name: "麟洛鄉", code: "linluo" },
        { id: "jiuru", name: "九如鄉", code: "jiuru" },
        { id: "ligang", name: "里港鄉", code: "ligang" },
        { id: "yanpu", name: "鹽埔鄉", code: "yanpu" },
        { id: "gaoshu", name: "高樹鄉", code: "gaoshu" },
        { id: "wanluan", name: "萬巒鄉", code: "wanluan" },
        { id: "neipu", name: "內埔鄉", code: "neipu" },
        { id: "zhutian", name: "竹田鄉", code: "zhutian" },
        { id: "xinpi", name: "新埤鄉", code: "xinpi" },
        { id: "fangliao", name: "枋寮鄉", code: "fangliao" },
        { id: "xinyuan", name: "新園鄉", code: "xinyuan" },
        { id: "kanding", name: "崁頂鄉", code: "kanding" },
        { id: "linbian", name: "林邊鄉", code: "linbian" },
        { id: "nanzhou", name: "南州鄉", code: "nanzhou" },
        { id: "jiadong", name: "佳冬鄉", code: "jiadong" },
        { id: "liuqui", name: "琉球鄉", code: "liuqui" },
        { id: "checheng", name: "車城鄉", code: "checheng" },
        { id: "manzhou", name: "滿州鄉", code: "manzhou" },
        { id: "fangshan", name: "枋山鄉", code: "fangshan" },
        { id: "sandimen", name: "三地門鄉", code: "sandimen" },
        { id: "wutai", name: "霧台鄉", code: "wutai" },
        { id: "majia", name: "瑪家鄉", code: "majia" },
        { id: "taiwu", name: "泰武鄉", code: "taiwu" },
        { id: "laiyi", name: "來義鄉", code: "laiyi" },
        { id: "chunri", name: "春日鄉", code: "chunri" },
        { id: "shizi", name: "獅子鄉", code: "shizi" },
        { id: "mudan", name: "牡丹鄉", code: "mudan" },
      ],
    },
    {
      id: "taitung",
      name: "臺東縣",
      code: "taitung",
      districts: [
        { id: "taitung", name: "臺東市", code: "taitung" },
        { id: "chenggong", name: "成功鎮", code: "chenggong" },
        { id: "guanshan", name: "關山鎮", code: "guanshan" },
        { id: "beinan", name: "卑南鄉", code: "beinan" },
        { id: "ludao", name: "綠島鄉", code: "ludao" },
        { id: "chishang", name: "池上鄉", code: "chishang" },
        { id: "donghe", name: "東河鄉", code: "donghe" },
        { id: "luye", name: "鹿野鄉", code: "luye" },
        { id: "yanping", name: "延平鄉", code: "yanping" },
        { id: "haiduan", name: "海端鄉", code: "haiduan" },
        { id: "dawu", name: "達仁鄉", code: "dawu" },
        { id: "jinfeng", name: "金峰鄉", code: "jinfeng" },
        { id: "daren", name: "大武鄉", code: "daren" },
        { id: "taimali", name: "太麻里鄉", code: "taimali" },
        { id: "lanyu", name: "蘭嶼鄉", code: "lanyu" },
        { id: "changbin", name: "長濱鄉", code: "changbin" },
      ],
    },
    {
      id: "hualien",
      name: "花蓮縣",
      code: "hualien",
      districts: [
        { id: "hualien", name: "花蓮市", code: "hualien" },
        { id: "fenglin", name: "鳳林鎮", code: "fenglin" },
        { id: "yuli", name: "玉里鎮", code: "yuli" },
        { id: "xincheng", name: "新城鄉", code: "xincheng" },
        { id: "jian", name: "吉安鄉", code: "jian" },
        { id: "shoufeng", name: "壽豐鄉", code: "shoufeng" },
        { id: "guangfu", name: "光復鄉", code: "guangfu" },
        { id: "fengbin", name: "豐濱鄉", code: "fengbin" },
        { id: "ruisui", name: "瑞穗鄉", code: "ruisui" },
        { id: "fuyuan", name: "富里鄉", code: "fuyuan" },
        { id: "xiulin", name: "秀林鄉", code: "xiulin" },
        { id: "wanrong", name: "萬榮鄉", code: "wanrong" },
        { id: "zhuoxi", name: "卓溪鄉", code: "zhuoxi" },
      ],
    },
    {
      id: "yilan",
      name: "宜蘭縣",
      code: "yilan",
      districts: [
        { id: "yilan", name: "宜蘭市", code: "yilan" },
        { id: "luodong", name: "羅東鎮", code: "luodong" },
        { id: "suao", name: "蘇澳鎮", code: "suao" },
        { id: "toucheng", name: "頭城鎮", code: "toucheng" },
        { id: "jiaoxi", name: "礁溪鄉", code: "jiaoxi" },
        { id: "zhuangwei", name: "壯圍鄉", code: "zhuangwei" },
        { id: "yuanshan", name: "員山鄉", code: "yuanshan" },
        { id: "dongshan_yilan", name: "冬山鄉", code: "dongshan_yilan" },
        { id: "wujie", name: "五結鄉", code: "wujie" },
        { id: "sanxing", name: "三星鄉", code: "sanxing" },
        { id: "datong_yilan", name: "大同鄉", code: "datong_yilan" },
        { id: "nanao", name: "南澳鄉", code: "nanao" },
      ],
    },
    {
      id: "penghu",
      name: "澎湖縣",
      code: "penghu",
      districts: [
        { id: "magong", name: "馬公市", code: "magong" },
        { id: "huxi", name: "湖西鄉", code: "huxi" },
        { id: "baisha", name: "白沙鄉", code: "baisha" },
        { id: "xiyu", name: "西嶼鄉", code: "xiyu" },
        { id: "wangAn", name: "望安鄉", code: "wangAn" },
        { id: "qimei", name: "七美鄉", code: "qimei" },
      ],
    },
    {
      id: "kinmen",
      name: "金門縣",
      code: "kinmen",
      districts: [
        { id: "jincheng", name: "金城鎮", code: "jincheng" },
        { id: "jinhu", name: "金湖鎮", code: "jinhu" },
        { id: "jinsha", name: "金沙鎮", code: "jinsha" },
        { id: "jinning", name: "金寧鄉", code: "jinning" },
        { id: "lieyu", name: "烈嶼鄉", code: "lieyu" },
        { id: "wuqiu", name: "烏坵鄉", code: "wuqiu" },
      ],
    },
    {
      id: "lienchiang",
      name: "連江縣",
      code: "lienchiang",
      districts: [
        { id: "nangan", name: "南竿鄉", code: "nangan" },
        { id: "beigan", name: "北竿鄉", code: "beigan" },
        { id: "juguang", name: "莒光鄉", code: "juguang" },
        { id: "dongyin", name: "東引鄉", code: "dongyin" },
      ],
    },
  ],
} as const;

export type Position = typeof POSITIONS[number]['value'];
export type Level = typeof LEVELS[number]['value'];
export type Gender = typeof GENDERS[number]['value'];
export type CityCode = typeof LOCATIONS.cities[number]['code'];
export type DistrictCode = typeof LOCATIONS.cities[number]['districts'][number]['code'];

export const findCityByCode = (code: CityCode) => 
  LOCATIONS.cities.find(city => city.code === code);

export const findDistrictByCode = (cityCode: CityCode, districtCode: DistrictCode) => 
  findCityByCode(cityCode)?.districts.find(district => district.code === districtCode);

export const findCityByName = (name: string) =>
  LOCATIONS.cities.find(city => city.name === name);

export const findDistrictByName = (cityName: string, districtName: string) =>
  findCityByName(cityName)?.districts.find(district => district.name === districtName); 

export type Role = typeof ROLES[number]['value'];